### ISSUE TITLE
import goodreads csv - Internal Server Error

### ISSUE THREAD

**Issue by internallabworks** [pickles4evaaaa/mybibliotheca#9]
Exported my goodreads library to csv, and tried importing it to Bibliotheca.
It worked for a bit and then it got internal server error.

Edit: Tried splitting the csv into small chunks, and it managed to import ~30 books at a time.
Would be good if it can import the entire csv in one go

**Comment by pickles4evaaaa** [comment]
@internallabworks I have updated the code so that the user can set the number of guniworkers. In theory, this should mean more stable csv imports as well as being able to process more books. Update to the latest code/ latest docker image and read below: 
Docker:
```yaml
version: '3.8'

services:
  bibliotheca:
    image: pickles4evaaaa/bibliotheca:latest
    container_name: bibliotheca
    ports:
      - "5053:5054"
    volumes:
      - bibliotheca_data:/app/data
    restart: unless-stopped
    environment:
      - TIMEZONE=America/Chicago  # ✅ Set your preferred timezone here
      - WORKERS=6  # Set the number of Gunicorn workers to 6

volumes:
  bibliotheca_data:

```

If running from source: 
```bash
   gunicorn -w NUMBER_OF_WORKERS -b 0.0.0.0:5054 run:app
   ```


Let me know if you notice any improvements. Of course, the more workers you run the more CPU and RAM will be required so keep that in mind.
